icons = [
    "paintbrush",
    "paintbrush-2",
    "slash",
    "settings",
    "folder-cog",
    "folder-symlink",
    "download-cloud",
    "alert-octagon",
    "wrench",
    "info",
    "check",
    "x"
]