[settings]
tiles_path = "not_initialized"
language = "en"
auto_start = true
auto_start_hide_settings = true # Hide settings when application autostarts
thumbnails_settings_enabled = true
updates_settings_enabled = true
experimental = false
snapping = 5
handle_height = 28.0 # Height of the handle in pixels
entry_limit = 100 # 0 = no limit (longer load time if you have a lot of files)
folder_style = 0

[appearance]
override = false # Override global values
theme = "dark" # 'light' and 'dark' options supported
color = "#50000000" # ARGB Color

# 0: None, The window background is Solid Color.
# 1: Transparent, The window background is Transparent.
# 2: Blur, The window background is a blur-behind.
# 3: AcrylicBlur, The window background is a blur-behind with a high blur radius. This level may fallback to Blur.
# 4: ForceAcrylicBlur, Force acrylic on some incompatible versions of Windows 10.
# 5. Mica, The window background is based on desktop wallpaper tint with a blur. This will only work on Windows 11.
transparency = 1