id = "00000000-0000-0000-0000-000000000000" # GUID of tile
name = "Tile Name"
path = ""
hidden = false # Tile is hidden

# 0 = top, 1 = bottom
edit_bar_alignment = 0

[size]
x = 100
y = 100

[location]
x = 100
y = 100

[appearance]
theme = "dark" # 'light' and 'dark' options supported
color = "#55000000" # ARGB Color