using Avalonia.Media;

namespace Avalonia.Tiels.Classes;

/// <summary>
/// Autogenerated Icons.
/// </summary>
public static class Icons
{
	public static readonly FontFamily FONT = new FontFamily("avares://Avalonia.Tiels/Assets#lucidelite");
	
    //Icons below are generated from build.py using include.toml. Changing anything below will be overwritten
    //!a
	public static readonly string WindowPlus = "󿞐";
	public static readonly string Paintbrush = "󿚐";
	public static readonly string PaintbrushAlt = "󿚑";
	public static readonly string Slash = "󿚒";
	public static readonly string Settings = "󿚓";
	public static readonly string FolderCog = "󿚔";
	public static readonly string FolderSymlink = "󿚕";
	public static readonly string DownloadCloud = "󿚖";
	public static readonly string AlertOctagon = "󿚗";
	public static readonly string Wrench = "󿚘";
	public static readonly string Info = "󿚙";
	public static readonly string Check = "󿚚";
	public static readonly string X = "󿚛";
	public static readonly string Image = "󿚜";
	public static readonly string ChevronDown = "󿚝";
	public static readonly string FolderOpen = "󿚞";
	public static readonly string RotateCw = "󿚟";
	public static readonly string EditAlt = "󿚠";
	public static readonly string ChevronUp = "󿚡";
	public static readonly string StickyNote = "󿚢";
	public static readonly string FileImage = "󿚣";
	//!a
}