using Avalonia.Media;

namespace Avalonia.Tiels.Classes;

/// <summary>
/// Autogenerated Icons.
/// </summary>
public class Icons
{
	public static readonly FontFamily FONT = new("avares://Avalonia.Tiels/Assets#lucidelite");
	
	private readonly string _glyph;
	private Icons(string glyph) => _glyph = glyph;
	public static explicit operator Icons(string glyph) => new(glyph);
	public static implicit operator string(Icons glyph) => glyph.ToString();
	public override string ToString() => _glyph;
	
    //Icons below are generated from build.py using include.toml. Changing anything below will be overwritten
    //!a
	public static readonly Icons WindowPlus = (Icons) "󿞐";
	public static readonly Icons Paintbrush = (Icons) "󿚐";
	public static readonly Icons PaintbrushAlt = (Icons) "󿚑";
	public static readonly Icons Slash = (Icons) "󿚒";
	public static readonly Icons Settings = (Icons) "󿚓";
	public static readonly Icons FolderCog = (Icons) "󿚔";
	public static readonly Icons FolderSymlink = (Icons) "󿚕";
	public static readonly Icons DownloadCloud = (Icons) "󿚖";
	public static readonly Icons AlertOctagon = (Icons) "󿚗";
	public static readonly Icons Wrench = (Icons) "󿚘";
	public static readonly Icons Info = (Icons) "󿚙";
	public static readonly Icons Check = (Icons) "󿚚";
	public static readonly Icons X = (Icons) "󿚛";
	public static readonly Icons Image = (Icons) "󿚜";
	public static readonly Icons ChevronDown = (Icons) "󿚝";
	public static readonly Icons FolderOpen = (Icons) "󿚞";
	public static readonly Icons RotateCw = (Icons) "󿚟";
	public static readonly Icons EditAlt = (Icons) "󿚠";
	public static readonly Icons ChevronUp = (Icons) "󿚡";
	public static readonly Icons StickyNote = (Icons) "󿚢";
	public static readonly Icons FileImage = (Icons) "󿚣";
	public static readonly Icons FlaskConical = (Icons) "󿚤";
	public static readonly Icons LayoutGrid = (Icons) "󿚥";
	public static readonly Icons ExternalLink = (Icons) "󿚦";
	public static readonly Icons MoreVertical = (Icons) "󿚧";
	public static readonly Icons Trash = (Icons) "󿚨";
	public static readonly Icons TrashAlt = (Icons) "󿚩";
	public static readonly Icons Move = (Icons) "󿚪";
	//!a
}