//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalonia.Tiels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avalonia.Tiels.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart enabled.
        /// </summary>
        public static string AutostartEnabled {
            get {
                return ResourceManager.GetString("AutostartEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes accepted.
        /// </summary>
        public static string ChangesAccepted {
            get {
                return ResourceManager.GetString("ChangesAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Directory Portal.
        /// </summary>
        public static string CreateDirectoryPortal {
            get {
                return ResourceManager.GetString("CreateDirectoryPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Floating Image.
        /// </summary>
        public static string CreateFloatingImage {
            get {
                return ResourceManager.GetString("CreateFloatingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateLabel {
            get {
                return ResourceManager.GetString("CreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sticky Note.
        /// </summary>
        public static string CreateNote {
            get {
                return ResourceManager.GetString("CreateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Tile.
        /// </summary>
        public static string CreateTile {
            get {
                return ResourceManager.GetString("CreateTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find default configuration file..
        /// </summary>
        public static string DefaultConfigMissingError {
            get {
                return ResourceManager.GetString("DefaultConfigMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default tiles directory.
        /// </summary>
        public static string DefaultTilesDirectory {
            get {
                return ResourceManager.GetString("DefaultTilesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling will increase performance.
        /// </summary>
        public static string EffectsPerformanceWarning {
            get {
                return ResourceManager.GetString("EffectsPerformanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental features.
        /// </summary>
        public static string ExperimentalFeatures {
            get {
                return ResourceManager.GetString("ExperimentalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide this window after application startup.
        /// </summary>
        public static string HideAtStartup {
            get {
                return ResourceManager.GetString("HideAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto hide buttons on Tile.
        /// </summary>
        public static string HideTileButtons {
            get {
                return ResourceManager.GetString("HideTileButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input!.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application language.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Images.
        /// </summary>
        public static string ManagementFloatingImages {
            get {
                return ResourceManager.GetString("ManagementFloatingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string ManagementLabel {
            get {
                return ResourceManager.GetString("ManagementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ManagementNotes {
            get {
                return ResourceManager.GetString("ManagementNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string ManagementTiles {
            get {
                return ResourceManager.GetString("ManagementTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [settings] or [appearance] table is missing. Configuration is possibly corrupted..
        /// </summary>
        public static string MissingSettingsAppearanceTableError {
            get {
                return ResourceManager.GetString("MissingSettingsAppearanceTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [settings] table is missing. Default configuration is possibly corrupted..
        /// </summary>
        public static string MissingSettingsTableError {
            get {
                return ResourceManager.GetString("MissingSettingsTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name of your new tile....
        /// </summary>
        public static string NameOfTileWatermark {
            get {
                return ResourceManager.GetString("NameOfTileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes.
        /// </summary>
        public static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen path doesn&apos;t exist.
        /// </summary>
        public static string PathDontExist {
            get {
                return ResourceManager.GetString("PathDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        public static string SettingsThumbnail {
            get {
                return ResourceManager.GetString("SettingsThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string SettingsUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapping to grid.
        /// </summary>
        public static string Snapping {
            get {
                return ResourceManager.GetString("Snapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Effects.
        /// </summary>
        public static string SpecialEffects {
            get {
                return ResourceManager.GetString("SpecialEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeMode {
            get {
                return ResourceManager.GetString("ThemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme of application/icons. If you have tile with dark background then dark and vice versa..
        /// </summary>
        public static string ThemeModeTooltip {
            get {
                return ResourceManager.GetString("ThemeModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string TilePath {
            get {
                return ResourceManager.GetString("TilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings: Tile.
        /// </summary>
        public static string TileSettingsLabel {
            get {
                return ResourceManager.GetString("TileSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency level can be changed in color option..
        /// </summary>
        public static string TransparencyChangedInColor {
            get {
                return ResourceManager.GetString("TransparencyChangedInColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency Type.
        /// </summary>
        public static string TransparencyMode {
            get {
                return ResourceManager.GetString("TransparencyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use global theme.
        /// </summary>
        public static string UseGlobalTheme {
            get {
                return ResourceManager.GetString("UseGlobalTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option only works on Windows 11..
        /// </summary>
        public static string WarnNewerSysReq {
            get {
                return ResourceManager.GetString("WarnNewerSysReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution! This option doesn&apos;t support most animated desktop software..
        /// </summary>
        public static string WarnOtherPrograms {
            get {
                return ResourceManager.GetString("WarnOtherPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution! Using other options than Solid or Transparent won&apos;t work on some systems and will fallback to these options..
        /// </summary>
        public static string WarnPossiblyUnsupported {
            get {
                return ResourceManager.GetString("WarnPossiblyUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string WindowTitleError {
            get {
                return ResourceManager.GetString("WindowTitleError", resourceCulture);
            }
        }
    }
}
