//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalonia.Tiels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avalonia.Tiels.Resources.Resources.pl", typeof(Resources_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom automatycznie po rozruchu.
        /// </summary>
        public static string AutostartEnabled {
            get {
                return ResourceManager.GetString("AutostartEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiany zostały pomyślnie wdrożone.
        /// </summary>
        public static string ChangesAccepted {
            get {
                return ResourceManager.GetString("ChangesAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz Portal do folderu.
        /// </summary>
        public static string CreateDirectoryPortal {
            get {
                return ResourceManager.GetString("CreateDirectoryPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz Unoszący Obraz.
        /// </summary>
        public static string CreateFloatingImage {
            get {
                return ResourceManager.GetString("CreateFloatingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz.
        /// </summary>
        public static string CreateLabel {
            get {
                return ResourceManager.GetString("CreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz Notatke.
        /// </summary>
        public static string CreateNote {
            get {
                return ResourceManager.GetString("CreateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz Nowy Kafelek.
        /// </summary>
        public static string CreateTile {
            get {
                return ResourceManager.GetString("CreateTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domyślne.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono domyślnego pliku konfiguracyjnego..
        /// </summary>
        public static string DefaultConfigMissingError {
            get {
                return ResourceManager.GetString("DefaultConfigMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domyślna lokalizacja kafelek.
        /// </summary>
        public static string DefaultTilesDirectory {
            get {
                return ResourceManager.GetString("DefaultTilesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłączenie poprawi wydajność.
        /// </summary>
        public static string EffectsPerformanceWarning {
            get {
                return ResourceManager.GetString("EffectsPerformanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz minimalną wysokość.
        /// </summary>
        public static string ExDisableWin32MinimumHeight {
            get {
                return ResourceManager.GetString("ExDisableWin32MinimumHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz Kategorie Miniaturek.
        /// </summary>
        public static string ExEnableThumbnailsCategory {
            get {
                return ResourceManager.GetString("ExEnableThumbnailsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz Uchwyty do Win32.
        /// </summary>
        public static string ExEnableWin32Hooks {
            get {
                return ResourceManager.GetString("ExEnableWin32Hooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcje eksperymentalne.
        /// </summary>
        public static string ExperimentalFeatures {
            get {
                return ResourceManager.GetString("ExperimentalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysokość uchwytu kafelka.
        /// </summary>
        public static string HandleSize {
            get {
                return ResourceManager.GetString("HandleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj okno ustawień po uruchomieniu.
        /// </summary>
        public static string HideAtStartup {
            get {
                return ResourceManager.GetString("HideAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj automatycznie przyciski na kafelkach.
        /// </summary>
        public static string HideTileButtons {
            get {
                return ResourceManager.GetString("HideTileButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe dane wejściowe!.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język programu.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pływające Obrazy.
        /// </summary>
        public static string ManagementFloatingImages {
            get {
                return ResourceManager.GetString("ManagementFloatingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie.
        /// </summary>
        public static string ManagementLabel {
            get {
                return ResourceManager.GetString("ManagementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatki.
        /// </summary>
        public static string ManagementNotes {
            get {
                return ResourceManager.GetString("ManagementNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kafelki.
        /// </summary>
        public static string ManagementTiles {
            get {
                return ResourceManager.GetString("ManagementTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje tabeli [settings] lub [appearance] w pliku konfiguracyjnym. Możliwe że plik konfiguracyjny uległ uszkodzeniu..
        /// </summary>
        public static string MissingSettingsAppearanceTableError {
            get {
                return ResourceManager.GetString("MissingSettingsAppearanceTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje tabeli [settings] w pliku konfiguracyjnym. Możliwe że plik konfiguracyjny uległ uszkodzeniu..
        /// </summary>
        public static string MissingSettingsTableError {
            get {
                return ResourceManager.GetString("MissingSettingsTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przytrzymaj tutaj żeby przesunąć kafelek..
        /// </summary>
        public static string MoveWindow {
            get {
                return ResourceManager.GetString("MoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa twojego nowego kafelka....
        /// </summary>
        public static string NameOfTileWatermark {
            get {
                return ResourceManager.GetString("NameOfTileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zmian.
        /// </summary>
        public static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrana ścieszka nie istnieje.
        /// </summary>
        public static string PathDontExist {
            get {
                return ResourceManager.GetString("PathDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygląd.
        /// </summary>
        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksperymentalne.
        /// </summary>
        public static string SettingsExperimental {
            get {
                return ResourceManager.GetString("SettingsExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogólne.
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniaturki.
        /// </summary>
        public static string SettingsThumbnail {
            get {
                return ResourceManager.GetString("SettingsThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizacje.
        /// </summary>
        public static string SettingsUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przyciąganie do siatki.
        /// </summary>
        public static string Snapping {
            get {
                return ResourceManager.GetString("Snapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string SnappingLabel {
            get {
                return ResourceManager.GetString("SnappingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efekty interfejsu użytkownika.
        /// </summary>
        public static string SpecialEffects {
            get {
                return ResourceManager.GetString("SpecialEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motyw.
        /// </summary>
        public static string ThemeMode {
            get {
                return ResourceManager.GetString("ThemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motyw aplikacji i ikonek. Jeśli naprzykład masz na kafelku czarne tło to motyw czarny i vice versa..
        /// </summary>
        public static string ThemeModeTooltip {
            get {
                return ResourceManager.GetString("ThemeModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj.
        /// </summary>
        public static string TileListLabel {
            get {
                return ResourceManager.GetString("TileListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka.
        /// </summary>
        public static string TilePath {
            get {
                return ResourceManager.GetString("TilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeźroczystość można zmienić w ustawieniach koloru..
        /// </summary>
        public static string TransparencyChangedInColor {
            get {
                return ResourceManager.GetString("TransparencyChangedInColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ przeźroczystości.
        /// </summary>
        public static string TransparencyMode {
            get {
                return ResourceManager.GetString("TransparencyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Używaj globalnego motywu.
        /// </summary>
        public static string UseGlobalTheme {
            get {
                return ResourceManager.GetString("UseGlobalTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta opcja działa tylko z Windows 11..
        /// </summary>
        public static string WarnNewerSysReq {
            get {
                return ResourceManager.GetString("WarnNewerSysReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwaga! Ta opcja nie jest obsługiwana przez większość programów umożliwiających animowane tapety..
        /// </summary>
        public static string WarnOtherPrograms {
            get {
                return ResourceManager.GetString("WarnOtherPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwaga! Używanie innej opcji niż Solidne tło czy Przeźroczyste może nie zadziałać na nie których systemach. Jeśl nie uda się ustawić to domyślnie program przywróci do powyższych opcji..
        /// </summary>
        public static string WarnPossiblyUnsupported {
            get {
                return ResourceManager.GetString("WarnPossiblyUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd: .
        /// </summary>
        public static string WindowTitleError {
            get {
                return ResourceManager.GetString("WindowTitleError", resourceCulture);
            }
        }
    }
}
