//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalonia.Tiels.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Avalonia.Tiels.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DefaultConfigMissingError {
            get {
                return ResourceManager.GetString("DefaultConfigMissingError", resourceCulture);
            }
        }
        
        public static string PathDontExist {
            get {
                return ResourceManager.GetString("PathDontExist", resourceCulture);
            }
        }
        
        public static string MissingSettingsTableError {
            get {
                return ResourceManager.GetString("MissingSettingsTableError", resourceCulture);
            }
        }
        
        public static string MissingSettingsAppearanceTableError {
            get {
                return ResourceManager.GetString("MissingSettingsAppearanceTableError", resourceCulture);
            }
        }
        
        public static string WindowTitleError {
            get {
                return ResourceManager.GetString("WindowTitleError", resourceCulture);
            }
        }
        
        public static string ChangesAccepted {
            get {
                return ResourceManager.GetString("ChangesAccepted", resourceCulture);
            }
        }
        
        public static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }
        
        public static string SettingsUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdates", resourceCulture);
            }
        }
        
        public static string CreateLabel {
            get {
                return ResourceManager.GetString("CreateLabel", resourceCulture);
            }
        }
        
        public static string CreateTile {
            get {
                return ResourceManager.GetString("CreateTile", resourceCulture);
            }
        }
        
        public static string CreateDirectoryPortal {
            get {
                return ResourceManager.GetString("CreateDirectoryPortal", resourceCulture);
            }
        }
        
        public static string CreateNote {
            get {
                return ResourceManager.GetString("CreateNote", resourceCulture);
            }
        }
        
        public static string CreateFloatingImage {
            get {
                return ResourceManager.GetString("CreateFloatingImage", resourceCulture);
            }
        }
        
        public static string ManagementLabel {
            get {
                return ResourceManager.GetString("ManagementLabel", resourceCulture);
            }
        }
        
        public static string ManagementTiles {
            get {
                return ResourceManager.GetString("ManagementTiles", resourceCulture);
            }
        }
        
        public static string ManagementNotes {
            get {
                return ResourceManager.GetString("ManagementNotes", resourceCulture);
            }
        }
        
        public static string ManagementFloatingImages {
            get {
                return ResourceManager.GetString("ManagementFloatingImages", resourceCulture);
            }
        }
        
        public static string AutostartEnabled {
            get {
                return ResourceManager.GetString("AutostartEnabled", resourceCulture);
            }
        }
        
        public static string HideAtStartup {
            get {
                return ResourceManager.GetString("HideAtStartup", resourceCulture);
            }
        }
        
        public static string SpecialEffects {
            get {
                return ResourceManager.GetString("SpecialEffects", resourceCulture);
            }
        }
        
        public static string ExperimentalFeatures {
            get {
                return ResourceManager.GetString("ExperimentalFeatures", resourceCulture);
            }
        }
        
        public static string EffectsPerformanceWarning {
            get {
                return ResourceManager.GetString("EffectsPerformanceWarning", resourceCulture);
            }
        }
        
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        public static string DefaultTilesDirectory {
            get {
                return ResourceManager.GetString("DefaultTilesDirectory", resourceCulture);
            }
        }
        
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        public static string TransparencyMode {
            get {
                return ResourceManager.GetString("TransparencyMode", resourceCulture);
            }
        }
        
        public static string ThemeMode {
            get {
                return ResourceManager.GetString("ThemeMode", resourceCulture);
            }
        }
        
        public static string ThemeModeTooltip {
            get {
                return ResourceManager.GetString("ThemeModeTooltip", resourceCulture);
            }
        }
        
        public static string UseGlobalTheme {
            get {
                return ResourceManager.GetString("UseGlobalTheme", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NameOfTileWatermark {
            get {
                return ResourceManager.GetString("NameOfTileWatermark", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string WarnPossiblyUnsupported {
            get {
                return ResourceManager.GetString("WarnPossiblyUnsupported", resourceCulture);
            }
        }
        
        public static string WarnNewerSysReq {
            get {
                return ResourceManager.GetString("WarnNewerSysReq", resourceCulture);
            }
        }
        
        public static string WarnOtherPrograms {
            get {
                return ResourceManager.GetString("WarnOtherPrograms", resourceCulture);
            }
        }
        
        public static string TransparencyChangedInColor {
            get {
                return ResourceManager.GetString("TransparencyChangedInColor", resourceCulture);
            }
        }
        
        public static string TilePath {
            get {
                return ResourceManager.GetString("TilePath", resourceCulture);
            }
        }
    }
}
