icons = [
    "paintbrush",
    "paintbrush-2",
    "slash",
    "settings",
    "folder-cog",
    "folder-symlink",
    "download-cloud",
    "alert-octagon",
    "wrench",
    "info",
    "check",
    "x",
    "image",
    "chevron-down",
    "folder-open",
    "rotate-cw",
    "edit-2",
    "chevron-up",
    "sticky-note",
    "file-image",
    "flask-conical",
    "layout-grid"
]

local_icons = [
    "window-plus"
]